name: visiontxt
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  footer: ^0.0.4
  go_router: ^16.1.0
  camera: ^0.11.2
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.2
  path: ^1.9.1
  path_provider: ^2.1.5
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_mesh_detection: ^0.4.1
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_selfie_segmentation: ^0.10.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/ml/

# ✅ Flutter launcher icons config should be here, not inside flutter:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
